# Generated by Django 3.0.14 on 2022-05-26 12:25

from django.db import migrations, models
import django.db.models.deletion
import series.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0007_auto_20220526_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'categoryserie',
                'verbose_name_plural': 'categoriesserie',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('rate', models.FloatField(default=0)),
                ('releaseyear', models.IntegerField(blank=True, default=2000)),
                ('country', models.CharField(blank=True, max_length=150)),
                ('thumbnail', models.ImageField(blank=True, upload_to='series/thumbnails')),
                ('desciption', models.TextField(blank=True, max_length=20000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('actors', models.ManyToManyField(blank=True, to='movies.Actors')),
                ('category', models.ManyToManyField(related_name='series', to='series.Categoryseries')),
                ('directors', models.ManyToManyField(blank=True, to='movies.Directors')),
                ('scriptwriter', models.ManyToManyField(blank=True, to='movies.Scriptwriter')),
                ('studio', models.ManyToManyField(blank=True, to='movies.Studio')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('thumbnail', models.ImageField(blank=True, upload_to='series/seasons/thumbnails')),
                ('desciption', models.TextField(blank=True, max_length=20000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='series.Serie')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('thumbnail', models.ImageField(blank=True, upload_to='series/episodes/thumbnails')),
                ('desciption', models.TextField(blank=True, max_length=20000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(blank=True, upload_to='movie/%y', validators=[series.validators.file_size])),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='series.Season')),
            ],
        ),
    ]
