# Generated by Django 3.0.14 on 2022-05-30 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': 'serie', 'verbose_name_plural': 'series'},
        ),
        migrations.AddField(
            model_name='episode',
            name='epinumber',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='series.Season'),
        ),
    ]
