# Generated by Django 3.0.14 on 2022-06-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20220530_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
