# Generated by Django 3.0.14 on 2022-05-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='category',
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(related_name='films', to='movies.Category'),
        ),
    ]
