# Generated by Django 3.0.14 on 2022-05-24 20:39

from django.db import migrations, models
import movies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220524_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='desciption',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.FileField(blank=True, upload_to='movie/%y', validators=[movies.validators.file_size]),
        ),
    ]
