# Generated by Django 3.0.14 on 2022-05-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_film_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='slug',
        ),
    ]
