# Generated by Django 3.0.14 on 2022-05-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_film_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='bio',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='actors',
            name='birthyear',
            field=models.IntegerField(blank=True, default=2000),
        ),
        migrations.AddField(
            model_name='actors',
            name='itfrom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='actors',
            name='photo',
            field=models.ImageField(blank=True, upload_to='actors/profile'),
        ),
    ]
