# Generated by Django 3.0.14 on 2022-05-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20220526_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='directors',
            name='bio',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='directors',
            name='birthyear',
            field=models.IntegerField(blank=True, default=2000),
        ),
        migrations.AddField(
            model_name='directors',
            name='itfrom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='directors',
            name='photo',
            field=models.ImageField(blank=True, upload_to='directors/profile'),
        ),
        migrations.AddField(
            model_name='scriptwriter',
            name='bio',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='scriptwriter',
            name='birthyear',
            field=models.IntegerField(blank=True, default=2000),
        ),
        migrations.AddField(
            model_name='scriptwriter',
            name='itfrom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='scriptwriter',
            name='photo',
            field=models.ImageField(blank=True, upload_to='writer/profile'),
        ),
        migrations.AddField(
            model_name='studio',
            name='desc',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='studio',
            name='itfrom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studio',
            name='logo',
            field=models.ImageField(blank=True, upload_to='studio/logo'),
        ),
        migrations.AddField(
            model_name='studio',
            name='sinceyear',
            field=models.IntegerField(blank=True, default=2000),
        ),
    ]
