# Generated by Django 3.0.14 on 2022-06-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20220526_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
