# Generated by Django 3.0.14 on 2022-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_serie_likes'),
        ('accounts', '0002_customer_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favoritesseries',
            field=models.ManyToManyField(to='series.Serie'),
        ),
    ]
